INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0000', '苹果', 'pingguo', 'pg', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0001', '梨', 'li', 'l', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0002', '榴莲', 'liulian', 'll', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0003', '芒果', 'mangguo', 'mg', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0004', '西瓜', 'xigua', 'xg', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0005', '百香果', 'baixiangguo', 'bxg', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0006', '柠檬', 'ningmeng', 'nm', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0007', '哈密瓜', 'hamigua', 'hmg', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0008', '火龙果', 'huolongguo', 'hlg', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0009', '葡萄', 'putao', 'pt', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0010', '香蕉', 'xiangjiao', 'xj', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0011', '蛇果', 'sheguo', 'sg', '2017-04-15', 'wxx', '2017-04-15', 'wxx');
INSERT INTO shop.goods (goods_no, goods_name, goods_py_name, goods_short_py_name, create_time, creator, update_time, updater) VALUES ('0012', '圣女果', 'shengnvguo', 'sng', '2017-04-15', 'wxx', '2017-04-15', 'wxx');

INSERT INTO shop.goods_price (goods_id, brand_id, price, create_time, creator, update_time, updater) VALUES (1, 1, 6, '2017-04-16', 'wxx', '2017-04-16', 'wxx');